[[redirects]]
  from = "/favicion.ico"
  to = "/favicion.ico"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
