name: build 

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn codegen
      - run: yarn build
